// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	_ "github.com/ChanJuiHuang/go-backend-framework/app/provider/internal/init"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, error) {
	logger := provideLogger()
	providerGormLogger := provideGormLogger(logger)
	db := provideDatabase(providerGormLogger)
	api := provideJson()
	client := provideRedis()
	validate := provideValidator()
	decoder := provideFormDecoder()
	transformer := provideModifier()
	syncedEnforcer := provideCasbin(db)
	application := provideApplication(logger, db, api, client, validate, decoder, transformer, syncedEnforcer)
	return application, nil
}
